if(NOT DEFINED CAI_BINARY_DIR OR CAI_BINARY_DIR STREQUAL "")
  message(FATAL_ERROR "CAI_BINARY_DIR is required")
endif()
if(NOT DEFINED CAI_C_PKT_SYSTEMS_PREFIX OR CAI_C_PKT_SYSTEMS_PREFIX STREQUAL "")
  message(FATAL_ERROR "CAI_C_PKT_SYSTEMS_PREFIX is required")
endif()
if(NOT DEFINED CAI_TARGET_ID)
  set(CAI_TARGET_ID "")
endif()
if(NOT DEFINED CAI_BUILD_SHARED)
  set(CAI_BUILD_SHARED ON)
endif()
if(NOT DEFINED CAI_BUILD_STATIC)
  set(CAI_BUILD_STATIC ON)
endif()
if(NOT DEFINED CAI_BUILD_LUA)
  set(CAI_BUILD_LUA OFF)
endif()
if(NOT DEFINED CAI_BUILD_EXAMPLES)
  set(CAI_BUILD_EXAMPLES ON)
endif()

set(build_ninja "${CAI_BINARY_DIR}/build.ninja")
if(NOT EXISTS "${build_ninja}")
  message(FATAL_ERROR "cpkt link target test requires Ninja build output")
endif()

file(STRINGS "${build_ninja}" ninja_lines ENCODING UTF-8)
set(cpkt_lib_dir "${CAI_C_PKT_SYSTEMS_PREFIX}/lib")

function(cai_ninja_link_edge cmake_target output_var)
  set(edge "")
  set(found_edge OFF)
  foreach(line IN LISTS ninja_lines)
    if(line MATCHES "^build .*: [A-Z_]*LINKER__${cmake_target}")
      set(edge "${line}\n")
      set(found_edge ON)
    elseif(found_edge)
      if(line MATCHES "^  ")
        string(APPEND edge "${line}\n")
      else()
        break()
      endif()
    endif()
  endforeach()
  if(edge STREQUAL "")
    message(FATAL_ERROR "missing Ninja link edge for ${cmake_target}")
  endif()
  set(${output_var} "${edge}" PARENT_SCOPE)
endfunction()

function(cai_require_contains label text needle)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${label} does not contain ${needle}:\n${text}")
  endif()
endfunction()

function(cai_require_not_contains label text needle)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "${label} unexpectedly contains ${needle}:\n${text}")
  endif()
endfunction()

set(shared_curl "${cpkt_lib_dir}/libcurl.so")
if(CAI_TARGET_ID MATCHES "darwin")
  set(shared_curl "${cpkt_lib_dir}/libcurl.dylib")
endif()
set(static_curl "${cpkt_lib_dir}/libcurl.a")
set(static_private_archives
  "${cpkt_lib_dir}/libcrypto.a"
  "${cpkt_lib_dir}/libnghttp2.a"
  "${cpkt_lib_dir}/libssh2.a"
  "${cpkt_lib_dir}/libssl.a"
  "${cpkt_lib_dir}/libz.a")

if(CAI_BUILD_SHARED)
  cai_ninja_link_edge(cai_shared shared_edge)
  cai_require_contains("cai_shared link edge" "${shared_edge}" "${shared_curl}")
  cai_require_not_contains("cai_shared link edge" "${shared_edge}" "${static_curl}")
  foreach(archive IN LISTS static_private_archives)
    cai_require_not_contains("cai_shared link edge" "${shared_edge}" "${archive}")
  endforeach()
  if(CAI_TARGET_ID MATCHES "darwin")
    cai_require_not_contains("cai_shared link edge" "${shared_edge}" "-ldl")
  endif()
endif()

if(CAI_BUILD_LUA AND CAI_BUILD_SHARED)
  cai_ninja_link_edge(cai_lua lua_edge)
  if(CAI_TARGET_ID MATCHES "darwin")
    cai_require_contains("cai_lua link edge" "${lua_edge}" "libcai.dylib")
  else()
    cai_require_contains("cai_lua link edge" "${lua_edge}" "libcai.so")
  endif()
  cai_require_not_contains("cai_lua link edge" "${lua_edge}" "${static_curl}")
  foreach(archive IN LISTS static_private_archives)
    cai_require_not_contains("cai_lua link edge" "${lua_edge}" "${archive}")
  endforeach()
  if(CAI_TARGET_ID MATCHES "darwin")
    cai_require_not_contains("cai_lua link edge" "${lua_edge}" "-ldl")
  endif()
endif()

if(CAI_BUILD_STATIC AND CAI_BUILD_EXAMPLES)
  cai_ninja_link_edge(cai_example_smhi_weather smhi_edge)
  cai_require_contains("smhi-weather link edge" "${smhi_edge}" "${static_curl}")
  cai_require_not_contains("smhi-weather link edge" "${smhi_edge}" "${shared_curl}")
endif()
