if(NOT DEFINED CAI_ASSET_INPUT OR CAI_ASSET_INPUT STREQUAL "")
  message(FATAL_ERROR "CAI_ASSET_INPUT is required")
endif()
if(NOT DEFINED CAI_ASSET_OUTPUT OR CAI_ASSET_OUTPUT STREQUAL "")
  message(FATAL_ERROR "CAI_ASSET_OUTPUT is required")
endif()
if(NOT DEFINED CAI_ASSET_MODE OR CAI_ASSET_MODE STREQUAL "")
  message(FATAL_ERROR "CAI_ASSET_MODE is required")
endif()
if(NOT EXISTS "${CAI_ASSET_INPUT}")
  message(FATAL_ERROR "asset input does not exist: ${CAI_ASSET_INPUT}")
endif()
if(NOT CAI_ASSET_MODE STREQUAL "raw" AND
   NOT CAI_ASSET_MODE STREQUAL "c-string")
  message(FATAL_ERROR "CAI_ASSET_MODE must be raw or c-string")
endif()

file(READ "${CAI_ASSET_INPUT}" _cai_asset_hex HEX)
string(TOLOWER "${_cai_asset_hex}" _cai_asset_hex)
if(CAI_ASSET_MODE STREQUAL "raw")
  if(_cai_asset_hex STREQUAL "")
    message(FATAL_ERROR "raw-byte asset input must not be empty")
  endif()
else()
  if(_cai_asset_hex MATCHES "00")
    message(FATAL_ERROR "C-string asset input must not contain NUL bytes")
  endif()

  # C-string mode appends the one generated terminator after the byte-exact
  # input. An empty C string is represented by this one byte.
  string(APPEND _cai_asset_hex "00")
endif()
string(LENGTH "${_cai_asset_hex}" _cai_asset_hex_length)
math(EXPR _cai_asset_byte_count "${_cai_asset_hex_length} / 2")
set(_cai_asset_byte_offset 0)
set(_cai_asset_contents "")
while(_cai_asset_byte_offset LESS _cai_asset_byte_count)
  set(_cai_asset_line "  ")
  set(_cai_asset_line_count 0)
  while(_cai_asset_line_count LESS 10 AND
        _cai_asset_byte_offset LESS _cai_asset_byte_count)
    math(EXPR _cai_asset_hex_offset "${_cai_asset_byte_offset} * 2")
    string(SUBSTRING "${_cai_asset_hex}" ${_cai_asset_hex_offset} 2
           _cai_asset_byte)
    if(_cai_asset_line_count GREATER 0)
      string(APPEND _cai_asset_line ", ")
    endif()
    string(APPEND _cai_asset_line "0x${_cai_asset_byte}")
    math(EXPR _cai_asset_byte_offset "${_cai_asset_byte_offset} + 1")
    math(EXPR _cai_asset_line_count "${_cai_asset_line_count} + 1")
  endwhile()
  if(_cai_asset_byte_offset LESS _cai_asset_byte_count)
    string(APPEND _cai_asset_line ",")
  endif()
  string(APPEND _cai_asset_contents "${_cai_asset_line}\n")
endwhile()

get_filename_component(_cai_asset_output_dir "${CAI_ASSET_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_cai_asset_output_dir}")
string(RANDOM LENGTH 24 ALPHABET "0123456789abcdef" _cai_asset_suffix)
set(_cai_asset_temporary "${CAI_ASSET_OUTPUT}.tmp-${_cai_asset_suffix}")
file(WRITE "${_cai_asset_temporary}" "${_cai_asset_contents}")
file(RENAME "${_cai_asset_temporary}" "${CAI_ASSET_OUTPUT}"
     RESULT _cai_asset_rename_result)
if(NOT _cai_asset_rename_result STREQUAL "0")
  file(REMOVE "${_cai_asset_temporary}")
  message(FATAL_ERROR
    "failed to publish generated asset ${CAI_ASSET_OUTPUT}: "
    "${_cai_asset_rename_result}")
endif()
